//
//  SCSVASTParserResponse.h
//  SCSCoreKit
//
//  Created by Thomas Geley on 22/03/2017.
//  Copyright © 2017 Smart AdServer. All rights reserved.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

@class SCSVASTModel;

/**
 Response of a SCSVASTParser parsing attempt.
 */
@interface SCSVASTParserResponse : NSObject

/// The data of the response if available.
@property (nonatomic, strong, nullable) SCSVASTModel *model;

/// An error associated with the parsing if available.
@property (nonatomic, strong, nullable) NSError *error;

- (instancetype)init NS_UNAVAILABLE;

/**
 Initialize a new SCSVASTParserResponse from model and error.
 
 @param model The VAST Model generated by the parser if available.
 @param error An error associated with the response if available.
 @return An initialized instance of SCSVASTParserResponse.
 */
- (instancetype)initWithModel:(nullable SCSVASTModel *)model error:(nullable NSError *)error NS_DESIGNATED_INITIALIZER;

@end

NS_ASSUME_NONNULL_END


