
# Define a global platform for your project.
platform :ios, '10.0'





target 'SimpleMediation' do
  pod 'Google-Mobile-Ads-SDK', '~> 9.4.0'
  pod 'Smart-Display-SDK', '~> 7.17.1'


end


target 'SimpleCSR' do
  pod 'FBAudienceNetwork', '~> 6.5.0'

end
