
# Define a global platform for your project.
platform :ios, '9.0'





target 'SimpleMediation' do
  pod 'Google-Mobile-Ads-SDK', '~> 8.5.0'
  pod 'Smart-Display-SDK', '~> 7.10.1'


end


target 'SimpleCSR' do
  pod 'FBAudienceNetwork', '~> 6.5.0'

end




