
# Define a global platform for your project.
platform :ios, '9.0'





target 'SimpleMediation' do
  pod 'Google-Mobile-Ads-SDK', '~> 7.67.0'
  pod 'FBAudienceNetwork', '~> 6.2.0'
  pod 'Smart-Display-SDK', '~> 7.8.0'


end


target 'SimpleCSR' do
  pod 'FBAudienceNetwork', '~> 6.2.0'

end




